export const MOCK_STUDENTS = [
  {
    id: 1,
    student_number: '2024-001',
    first_name: 'Juan',
    last_name: 'Dela Cruz',
    email: 'juan.cruz@ccs.edu',
    program: 'BS Computer Science',
    year_level: 3,
    faculty_id: 1,
    gender: 'Male',
    status: 'Active',
    gpa: '3.75',
    created_at: '2020-08-15',
  },
  {
    id: 2,
    student_number: '2024-002',
    first_name: 'Maria',
    last_name: 'Santos',
    email: 'maria.santos@ccs.edu',
    program: 'BS Information Technology',
    year_level: 2,
    faculty_id: 2,
    gender: 'Female',
    status: 'Active',
    gpa: '3.85',
    created_at: '2021-08-15',
  },
  {
    id: 3,
    student_number: '2024-003',
    first_name: 'Pedro',
    last_name: 'Reyes',
    email: 'pedro.reyes@ccs.edu',
    program: 'BS Computer Science',
    year_level: 4,
    faculty_id: 1,
    gender: 'Male',
    status: 'Active',
    gpa: '3.92',
    created_at: '2019-08-15',
  },
  {
    id: 4,
    student_number: '2024-004',
    first_name: 'Ana',
    last_name: 'Garcia',
    email: 'ana.garcia@ccs.edu',
    program: 'BS Data Science',
    year_level: 3,
    faculty_id: 3,
    gender: 'Female',
    status: 'Active',
    gpa: '3.65',
    created_at: '2020-08-15',
  },
  {
    id: 5,
    student_number: '2024-005',
    first_name: 'Jose',
    last_name: 'Rodriguez',
    email: 'jose.rodriguez@ccs.edu',
    program: 'BS Computer Science',
    year_level: 1,
    faculty_id: 1,
    gender: 'Male',
    status: 'Probation',
    gpa: '2.45',
    created_at: '2023-08-15',
  },
  {
    id: 6,
    student_number: '2024-006',
    first_name: 'Carmen',
    last_name: 'Mendoza',
    email: 'carmen.mendoza@ccs.edu',
    program: 'BS Information Technology',
    year_level: 2,
    faculty_id: 2,
    gender: 'Female',
    status: 'Active',
    gpa: '3.55',
    created_at: '2021-08-15',
  },
  {
    id: 7,
    student_number: '2024-007',
    first_name: 'Miguel',
    last_name: 'Torres',
    email: 'miguel.torres@ccs.edu',
    program: 'BS Cyber Security',
    year_level: 3,
    faculty_id: 4,
    gender: 'Male',
    status: 'Active',
    gpa: '3.80',
    created_at: '2020-08-15',
  },
  {
    id: 8,
    student_number: '2024-008',
    first_name: 'Luz',
    last_name: 'Flores',
    email: 'luz.flores@ccs.edu',
    program: 'BS Computer Science',
    year_level: 4,
    faculty_id: 1,
    gender: 'Female',
    status: 'Graduated',
    gpa: '3.95',
    created_at: '2019-08-15',
  },
];

export const MOCK_FACULTY = [
  {
    id: 1,
    first_name: 'Ricardo',
    last_name: 'Martinez',
    employee_number: 'EMP-001',
    department: 'Computer Science',
    position: 'Professor',
    specialization: 'Artificial Intelligence',
    gender: 'Male',
    hire_date: '2018-08-15',
    user_id: 101,
    created_at: '2018-08-15',
    email: 'ricardo.martinez@ccs.edu'
  },
  {
    id: 2,
    first_name: 'Sofia',
    last_name: 'Bautista',
    employee_number: 'EMP-002',
    department: 'Information Technology',
    position: 'Associate Professor',
    specialization: 'Database Systems',
    gender: 'Female',
    hire_date: '2019-01-20',
    user_id: 102,
    created_at: '2019-01-20',
    email: 'sofia.bautista@ccs.edu'
  },
  {
    id: 3,
    first_name: 'Antonio',
    last_name: 'Lopez',
    employee_number: 'EMP-003',
    department: 'Computer Science',
    position: 'Professor',
    specialization: 'Machine Learning',
    gender: 'Male',
    hire_date: '2017-06-10',
    user_id: 103,
    created_at: '2017-06-10',
    email: 'antonio.lopez@ccs.edu'
  },
  {
    id: 4,
    first_name: 'Elena',
    last_name: 'Cruz',
    employee_number: 'EMP-004',
    department: 'Data Science',
    position: 'Assistant Professor',
    specialization: 'Data Analytics',
    gender: 'Female',
    hire_date: '2021-03-05',
    user_id: 104,
    created_at: '2021-03-05',
    email: 'elena.cruz@ccs.edu'
  },
  {
    id: 5,
    first_name: 'Manuel',
    last_name: 'Filipino',
    employee_number: 'EMP-005',
    department: 'Cyber Security',
    position: 'Associate Professor',
    specialization: 'Network Security',
    gender: 'Male',
    hire_date: '2019-09-12',
    user_id: 105,
    created_at: '2019-09-12',
    email: 'manuel.filipino@ccs.edu'
  },
  {
    id: 6,
    first_name: 'Theresa',
    last_name: 'Dimagiba',
    employee_number: 'EMP-006',
    department: 'Information Technology',
    position: 'Professor',
    specialization: 'Web Development',
    gender: 'Female',
    hire_date: '2016-02-28',
    user_id: 106,
    created_at: '2016-02-28',
    email: 'theresa.dimagiba@ccs.edu'
  },
  {
    id: 7,
    first_name: 'Ferdinand',
    last_name: 'Santos',
    employee_number: 'EMP-007',
    department: 'Computer Science',
    position: 'Assistant Professor',
    specialization: 'Software Engineering',
    gender: 'Male',
    hire_date: '2022-07-18',
    user_id: 107,
    created_at: '2022-07-18',
    email: 'ferdinand.santos@ccs.edu'
  },
  {
    id: 8,
    first_name: 'Gloria',
    last_name: 'Rivera',
    employee_number: 'EMP-008',
    department: 'Data Science',
    position: 'Professor',
    specialization: 'Big Data',
    gender: 'Female',
    hire_date: '2015-11-03',
    user_id: 108,
    created_at: '2015-11-03',
    email: 'gloria.rivera@ccs.edu'
  }
];
