export const MOCK_STUDENTS = [
  {
    id: 1,
    student_number: '2024-001',
    first_name: 'Juan',
    last_name: 'Dela Cruz',
    email: 'juan.cruz@ccs.edu',
    program: 'BS Computer Science',
    year_level: 3,
    faculty_id: 1,
    gender: 'Male',
    status: 'Active',
    gpa: '3.75',
    created_at: '2020-08-15',
  },
  {
    id: 2,
    student_number: '2024-002',
    first_name: 'Maria',
    last_name: 'Santos',
    email: 'maria.santos@ccs.edu',
    program: 'BS Information Technology',
    year_level: 2,
    faculty_id: 2,
    gender: 'Female',
    status: 'Active',
    gpa: '3.85',
    created_at: '2021-08-15',
  },
  {
    id: 3,
    student_number: '2024-003',
    first_name: 'Pedro',
    last_name: 'Reyes',
    email: 'pedro.reyes@ccs.edu',
    program: 'BS Computer Science',
    year_level: 4,
    faculty_id: 1,
    gender: 'Male',
    status: 'Active',
    gpa: '3.92',
    created_at: '2019-08-15',
  },
  {
    id: 4,
    student_number: '2024-004',
    first_name: 'Ana',
    last_name: 'Garcia',
    email: 'ana.garcia@ccs.edu',
    program: 'BS Data Science',
    year_level: 3,
    faculty_id: 3,
    gender: 'Female',
    status: 'Active',
    gpa: '3.65',
    created_at: '2020-08-15',
  },
  {
    id: 5,
    student_number: '2024-005',
    first_name: 'Jose',
    last_name: 'Rodriguez',
    email: 'jose.rodriguez@ccs.edu',
    program: 'BS Computer Science',
    year_level: 1,
    faculty_id: 1,
    gender: 'Male',
    status: 'Probation',
    gpa: '2.45',
    created_at: '2023-08-15',
  },
  {
    id: 6,
    student_number: '2024-006',
    first_name: 'Carmen',
    last_name: 'Mendoza',
    email: 'carmen.mendoza@ccs.edu',
    program: 'BS Information Technology',
    year_level: 2,
    faculty_id: 2,
    gender: 'Female',
    status: 'Active',
    gpa: '3.55',
    created_at: '2021-08-15',
  },
  {
    id: 7,
    student_number: '2024-007',
    first_name: 'Miguel',
    last_name: 'Torres',
    email: 'miguel.torres@ccs.edu',
    program: 'BS Cyber Security',
    year_level: 3,
    faculty_id: 4,
    gender: 'Male',
    status: 'Active',
    gpa: '3.80',
    created_at: '2020-08-15',
  },
  {
    id: 8,
    student_number: '2024-008',
    first_name: 'Luz',
    last_name: 'Flores',
    email: 'luz.flores@ccs.edu',
    program: 'BS Computer Science',
    year_level: 4,
    faculty_id: 1,
    gender: 'Female',
    status: 'Graduated',
    gpa: '3.95',
    created_at: '2019-08-15',
  },
];

export const MOCK_FACULTY = [
  {
    id: 1,
    first_name: 'Dr. John',
    last_name: 'Smith',
    email: 'john.smith@ccs.edu',
    department: 'Computer Science',
  },
  {
    id: 2,
    first_name: 'Prof. Jane',
    last_name: 'Doe',
    email: 'jane.doe@ccs.edu',
    department: 'Information Technology',
  },
  {
    id: 3,
    first_name: 'Dr. Alan',
    last_name: 'Turing',
    email: 'alan.turing@ccs.edu',
    department: 'Data Science',
  },
  {
    id: 4,
    first_name: 'Prof. Ada',
    last_name: 'Lovelace',
    email: 'ada.lovelace@ccs.edu',
    department: 'Cyber Security',
  },
];